POST http://localhost:8080/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MzY5NzQ0MjQsInVzZXJJZCI6MX0._REUhk2lRb-lzAXy21Rw5-oOsGZA_RawmG4YSjKHAOs

{
    "title": "Test Post 2",
    "description": "Test post",
    "dateTime": "2025-01-14T15:30:00.000Z"
}